Add CMake build system and move/rename examples
dkfans/ADiKtEd pull request #45
Opened 2022-03-09 12:59 UTC by jopadan

2022-03-09 16:45 UTC, Loobinex commented
@jopadan I used to build adikted by typing 'make all' in WSL in adikted/mapslang. Trying to build your PR and it does not find a makefile. How can one build now?

2022-03-09 18:05 UTC, dotted commented
Good work, just fix the `${SDL_LIBRARIES}` issue and I will be happy to merge this.

2022-03-09 18:14 UTC, dotted commented
It would be nice if we could retain the possibility of building `mapslang` directly from within the `mapslang` folder, instead of having to build from the parent directory.

2022-03-09 18:17 UTC, dotted requested changes

2022-03-09 18:17 UTC, dotted commented on CMakeLists.txt
> +target_link_libraries( viewmap PUBLIC adikted m dl ${SDL_LIBRARIES})
Change `${SDL_LIBRARIES}` to `${SDL_LIBRARY}` as it only exists in CMake 3.19 and onwards

2022-03-09 18:17 UTC, dotted commented on CMakeLists.txt
> +target_link_libraries( putemple PRIVATE adikted m dl ${SDL_LIBRARIES})
Change `${SDL_LIBRARIES}` to `${SDL_LIBRARY}` as it only exists in CMake 3.19 and onwards

2022-03-09 18:17 UTC, dotted commented on CMakeLists.txt
> +find_package( SDL REQUIRED SDL::Main )
Consider making it optional so if SDL is not found the `viewmap` and `putemple` example projects are not built. Not super important though.

2022-03-11 15:33 UTC, closed without merging

2022-03-28 17:11 UTC, dotted commented
Continued in #48