Add more/wanted slabs
dkfans/ADiKtEd pull request #5
Opened 2020-09-29 20:26 UTC by AdamPlenty

2021-07-11 01:27 UTC, dotted commented
Is this still being worked on?

2021-07-11 01:41 UTC, AdamPlenty commented
> 
> 
> Is this still being worked on?

I almost forgot about this! I think the only thing missing is the description, but I don't know how to do that.

2021-11-17 01:09 UTC, Loobinex commented
Placing it all seems to work well, so if the slab type is added to KeeperFX, could be merged, see:
https://github.com/dkfans/keeperfx/pull/915

2021-11-17 05:23 UTC, dotted requested changes
Just minor things, looks good otherwise

2021-11-17 05:23 UTC, dotted commented on libadikted/obj_column.c
> +    case 54:
Add `#define SLAB_TYPE_PURPLE_PATH    0x36` in `obj_slabs.h` and use that instead so magic numbers is avoided.

2021-11-17 05:23 UTC, dotted commented on mapslang/scr_list.c
> -        0,SLAB_TYPE_GUARDPOST,17);
As above don't use magic numbers.

2021-11-17 05:23 UTC, dotted commented on mapslang/map.hlp
> +Unknown slab
Missing `\r` and `\s`?

2022-03-28 16:41 UTC, PieterVdc commented
@dotted I implemented the requested changes on this one

2022-03-28 16:43 UTC, dotted approved these changes

2022-03-28 16:45 UTC, merged